dist: xenial
language: csharp
mono: none
sudo: required
env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
before_install:
  - sudo snap set system experimental.parallel-instances=true
install:
  - sudo snap install dotnet-sdk_2 --classic
  - sudo snap install dotnet-sdk_3 --beta --classic
  - sudo snap alias dotnet-sdk_2.dotnet dotnet2
  - sudo snap alias dotnet-sdk_3.dotnet dotnet3
script:
  - dotnet2 test --framework=netcoreapp2.0
  - dotnet3 test --framework=netcoreapp3.0
  - dotnet3 pack
