dist: xenial
language: csharp
mono: none
sudo: required
env:
  - SDK_VERSION="" DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
  - SDK_VERSION="--beta" DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
install:
  - sudo snap install dotnet-sdk $SDK_VERSION --classic
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet tool install Cake.Tool
script:
  - dotnet cake --target=test
  - dotnet cake --target=pack
