dist: xenial
language: csharp
mono: none
sudo: required
env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
before_install:
  - sudo apt update
  - sudo apt install snapd snap
  - sudo snap set system experimental.parallel-instances=true
  - sudo snap --version
install:
  - sudo snap install dotnet-sdk_2 --classic
  - sudo snap install dotnet-sdk_3 --beta --classic
script:
  - sudo snap alias dotnet-sdk_2.dotnet dotnet
  - dotnet test --framework=netcoreapp2.0
  - sudo snap alias dotnet-sdk_3.dotnet dotnet
  - dotnet test --framework=netcoreapp3.0
  - dotnet pack
